<?php

namespace ContainerHjc0QZa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TdwSeEJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TdwSeEJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TdwSeEJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\MainController::HomePage' => ['privates', '.service_locator.s48JJdA.App\\Controller\\MainController::HomePage()', 'getMainControllerHomePageService', true],
            'App\\Controller\\StarshipApiController::getCollection' => ['privates', '.service_locator.aCzovii.App\\Controller\\StarshipApiController::getCollection()', 'getStarshipApiControllergetCollectionService', true],
            'App\\Controller\\StarshipApiController::get' => ['privates', '.service_locator.3njGSgp.App\\Controller\\StarshipApiController::get()', 'getStarshipApiControllergetService', true],
            'App\\Controller\\StarshipController::show' => ['privates', '.service_locator.3njGSgp.App\\Controller\\StarshipController::show()', 'getStarshipControllershowService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\MainController:HomePage' => ['privates', '.service_locator.s48JJdA.App\\Controller\\MainController::HomePage()', 'getMainControllerHomePageService', true],
            'App\\Controller\\StarshipApiController:getCollection' => ['privates', '.service_locator.aCzovii.App\\Controller\\StarshipApiController::getCollection()', 'getStarshipApiControllergetCollectionService', true],
            'App\\Controller\\StarshipApiController:get' => ['privates', '.service_locator.3njGSgp.App\\Controller\\StarshipApiController::get()', 'getStarshipApiControllergetService', true],
            'App\\Controller\\StarshipController:show' => ['privates', '.service_locator.3njGSgp.App\\Controller\\StarshipController::show()', 'getStarshipControllershowService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\MainController::HomePage' => '?',
            'App\\Controller\\StarshipApiController::getCollection' => '?',
            'App\\Controller\\StarshipApiController::get' => '?',
            'App\\Controller\\StarshipController::show' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\MainController:HomePage' => '?',
            'App\\Controller\\StarshipApiController:getCollection' => '?',
            'App\\Controller\\StarshipApiController:get' => '?',
            'App\\Controller\\StarshipController:show' => '?',
        ]);
    }
}
