<?php

namespace ContainerHjc0QZa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3njGSgpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3njGSgp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3njGSgp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\StarshipRepository', 'getStarshipRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\StarshipRepository',
        ]);
    }
}
