<?php

namespace ContainerHjc0QZa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStarshipApiControllergetCollectionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aCzovii.App\Controller\StarshipApiController::getCollection()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aCzovii.App\\Controller\\StarshipApiController::getCollection()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', true],
            'repository' => ['privates', 'App\\Repository\\StarshipRepository', 'getStarshipRepositoryService', true],
        ], [
            'logger' => '?',
            'repository' => 'App\\Repository\\StarshipRepository',
        ]))->withContext('App\\Controller\\StarshipApiController::getCollection()', $container);
    }
}
