<?php

namespace ContainerHjc0QZa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStarshipControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3njGSgp.App\Controller\StarshipController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3njGSgp.App\\Controller\\StarshipController::show()'] = ($container->privates['.service_locator.3njGSgp'] ?? $container->load('get_ServiceLocator_3njGSgpService'))->withContext('App\\Controller\\StarshipController::show()', $container);
    }
}
