<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWzjSoNZ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWzjSoNZ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWzjSoNZ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWzjSoNZ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWzjSoNZ\App_KernelDevDebugContainer([
    'container.build_hash' => 'WzjSoNZ',
    'container.build_id' => '6bf13f34',
    'container.build_time' => 1774938373,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWzjSoNZ');
